/**
 * Images should be stored in the `App/Images` directory and referenced using variables defined here.
 */


export default {
  logoWhite: require('../assets/images/Common/logo-white.png'),
  lana_icon: require('../assets/images/Common/lana_icon.png'),
  greenBg: require('../assets/images/Common/greenBg.png'),
  squareBg: require('../assets/images/Common/squareBackground.png'),
  grayBg: require('../assets/images/Common/graybg.png'),
  rocker: require('../assets/images/Common/rockerBg.png'),
  rockerSmall: require('../assets/images/Common/rocketSmall.png'),
  rockerSmall2: require('../assets/images/Common/rocketSmall2.png'),
  callBtn: require('../assets/images/Common/callBtn.png'),
  iAmNewBtn : require("../assets/images/Common/button-soy-nuevo.png"),
  knowOurPlansBtn : require("../assets/images/Common/button-conoce.png"),
  greenHeader : require("../assets/images/Common/greenheaderbg.png"),
  greenHeaderLines : require("../assets/images/Common/background.png"),
  whiteBody : require("../assets/images/Common/rectangle.png"),
  signInBtn : require("../assets/images/Common/signInbtn.png"),
  registryBtn : require("../assets/images/Common/button-registry.png"),
  avatar: require("../assets/images/Common/avatar.png"),
  icon_signup: require("../assets/images/Common/1_icon_signup.png"),
  icon_document: require("../assets/images/Common/2_icon_document.png"),
  icon_review: require("../assets/images/Common/3_icon_review.png"),
  icon_test: require("../assets/images/Common/4_icon_test.png"),
  icon_send_IRS: require("../assets/images/Common/5_icon_send_IRS.png"),
  standbg: require("../assets/images/Common/standbg.png"),
  callBottom : require('../assets/images/Common/callBottom.png'),
  plan1 : require('../assets/images/Common/plan1.png'),
  plan1E : require('../assets/images/Common/plan1E.png'),
  plan2 : require('../assets/images/Common/plan2.png'),
  plan2E : require('../assets/images/Common/plan2E.png'),
  plan3 : require('../assets/images/Common/plan3.png'),
  plan3E : require('../assets/images/Common/plan3E.png'),
  plan4 : require('../assets/images/Common/plan4.png'),
  plan4E : require('../assets/images/Common/plan4E.png'),
  plansBg : require('../assets/images/Common/plansBg.png'),
  characterPlans : require('../assets/images/Common/characterPlans.png'),
  loading: require('../assets/images/Common/loading-money.gif'),
}
